apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-frontend
  template:
    metadata:
      labels:
        app: kube-frontend
    spec:
      containers:
        - name: kube-frontend
          image: yourdockerhub/kube-frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_ISSUANCE_URL
              value: http://issuance-service:4001
            - name: REACT_APP_VERIFY_URL
              value: http://verification-service:4002
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: kube-frontend
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
