apiVersion: apps/v1
kind: Deployment
metadata:
  name: issuance-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: issuance
  template:
    metadata:
      labels:
        app: issuance
    spec:
      containers:
        - name: issuance
          image: yourdockerhub/issuance-service:latest
          ports:
            - containerPort: 4001
          env:
            - name: WORKER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MONGO_URI
              value: mongodb://mongo:27017/issuance
            - name: VERIFICATION_SERVICE_URL
              value: http://verification-service:4002/ingest
---
apiVersion: v1
kind: Service
metadata:
  name: issuance-service
spec:
  selector:
    app: issuance
  ports:
    - port: 4001
      targetPort: 4001
  type: ClusterIP
