name: CI/CD Pipeline 

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Build issuance service
        working-directory: ./backend/issuance-service
        run: |
          npm install

      - name: Build verification service
        working-directory: ./backend/verification-service
        run: |
          npm install

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend Docker images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/issuance-service:latest ./backend/issuance-service
          docker push ${{ secrets.DOCKER_USERNAME }}/issuance-service:latest

          docker build -t ${{ secrets.DOCKER_USERNAME }}/verification-service:latest ./backend/verification-service
          docker push ${{ secrets.DOCKER_USERNAME }}/verification-service:latest
